server:
  port: 8002
spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
  profiles:
    active: native
eureka:
  instance:
    hostname: http://localhost:8001/
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${eureka.instance.hostname}/eureka/
    registry-fetch-interval-seconds: 30
    fetch-registry: true

