spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/matchmaking?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    hikari:
      connection-timeout: 300
      idle-timeout: 60000
      max-lifetime: 30
      maximum-pool-size: 10
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
    timeout: 8000
logging:
  level:
    com:
      example:
        demo:
          dao: debug #xml对应的接口所在包
white:
  name: /login,/register